# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore PlatesOrganiser.sln
    - name: Build
      run: dotnet build --no-restore PlatesOrganiser.sln

    - name: API Integration Tests
      run: dotnet test tests/PlatesOrganiser.API.Integration.Tests/PlatesOrganiser.API.Integration.Tests.csproj --no-build --verbosity normal
    - name: Application Unit Tests
      run: dotnet test tests/PlatesOrganiser.Application.Unit.Tests/PlatesOrganiser.Application.Unit.Tests.csproj --no-build --verbosity normal
    - name: Infrastructure Integration Tests
      run: dotnet test tests/PlatesOrganiser.Infrastructure.Integration.Tests/PlatesOrganiser.Infrastructure.Integration.Tests.csproj --no-build --verbosity normal
